CREATE TABLE department
(
    id       NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY(),
    name     VARCHAR2(30) NOT NULL,
    location VARCHAR2(30) NOT NULL,

    CONSTRAINT department_id_pk PRIMARY KEY (id)
);

COMMENT ON TABLE department IS 'Department table that shows details of department where employees work.';
COMMENT ON COLUMN department.id IS 'Primary key column of department table.';
COMMENT ON COLUMN department.name IS 'A not null column that shows name of a department.';
COMMENT ON COLUMN department.location IS 'Location where a department is located.';